version: ‘3’

services:
docker-mysql:
image: mysql:latest
spring-boot-jpa-docker-webapp:
depends_on:
  - docker-mysql
ports:
  - 8080:8080
environment:
  - DATABASE_HOST=mysqldb
  - DATABASE_USER=root
  - DATABASE_PASSWORD=root
  - DATABASE_NAME=employeedb
  - DATABASE_PORT=3306